# https://aka.ms/yaml

trigger:
- master
- devel

jobs:
  - job:  master
    pool:
        vmImage: 'Ubuntu-16.04'

    variables:
        system.debug: 'false'

    displayName: 'Android Master'
    timeoutInMinutes: 360
    steps:
        - script: |
            set -eux
            df -h
            sudo fdisk -l
            sudo mkdir /data/aosp
            sudo chown $USER /data/aosp
            docker info
            git config --global user.name $USER
            make user
          displayName: 'Preparing image'

        - script: |
            make volumes ccache ccache.stats
            make ccache.clear
            make ccache.config
            make ccache ccache.stats
          displayName: 'Setting ccache'

        - script: |
            make master.mirror-root-volume master.mirror-root
            du -sh /data/aosp/mirror.root/master
            df -h /data
          displayName: 'Preparing Root Mirror'

        - script: |
            make master.mirror-volume master.mirror
            du -sh /data/aosp/mirror/master
            df -h /data
          displayName: 'Preparing Mirror'

        - script: |
            make master.source-root-volume master.source.root
            du -sh /data/aosp/source.root/master/
            df -h /data
          displayName: 'Master Root Source'

        - script: |
            make master.source-volume master.source
            du -sh /data/aosp/source/master
            df -h /data
            du -sh /data/aosp/aosp_out
          displayName: 'Master Source'

        - script: |
            make master.sync
          displayName: 'Master Sync'

        - script: |
            make master.build BUILD_TARGET=nothing
          displayName: 'Build nothing'
