ARG image
FROM $image:linux
ARG userid
ARG groupid
ARG username
COPY entrypoint.sh .gitconfig /root/
RUN set -eux; \
    curl -o /usr/local/bin/repo https://storage.googleapis.com/git-repo-downloads/repo; \
    chmod a+x /usr/local/bin/repo; \
    groupadd -g $groupid $username; \
    useradd -m -u $userid -g $groupid $username; \
    echo $username >/root/username; \
	git config --global color.ui false; \
    cp /root/.gitconfig /home/$username/; \
    chown $userid:$groupid /home/$username/.gitconfig; \
    echo DONE
ENTRYPOINT ["/root/entrypoint.sh"]
CMD ["build"]
