FROM ubuntu:18.04
RUN set -eux;\
 export http_proxy=$HTTP_PROXY; \
 apt-get update; apt-get install --no-install-recommends -y \
 bison \
 build-essential \
 ccache \
 curl \
 flex \
 g++-multilib \
 gcc-multilib \
 git-core \
 gnupg \
 gperf \
 lib32ncurses5-dev \
 lib32z-dev \
 libc6-dev-i386 \
 libgl1-mesa-dev \
 libpulse0 \
 libqt5gui5 \
 libqt5svg5 \
 libx11-dev \
 libxml2-utils \
 protobuf-compiler \
 python \
 python-dev \
 python-pip \
 python-protobuf \
 python-virtualenv \
 python3 \
 rsync \
 sudo \
 unzip \
 x11proto-core-dev \
 xsltproc \
 zip \
 zlib1g-dev \
    ;apt-get clean;rm -rf /var/lib/apt/lists/*;\
    echo DONE
